#include <iostream>
#include <iomanip>
using namespace std;
int main()
{    // A CODE FOR CALCULATOR 
	cout<<" ."<<setw(44)<<setfill('-')<<",\n"
	<<'|'<<" ."<<setw(43)<<setfill('-')<<". |\n"
	<<"| | _~_"<<setw(39)<<setfill(' ')<<"| |\n"
	<<"| |  \\/  NUCES Instruments"<<setw(20)<<setfill(' ')<<"T I - 8 6 | |\n"
	<<"| | ."<<setw(41)<<setfill('-')<<", | |\n"
	<<"| | |"<<setw(41)<<setfill(' ')<<"| | |\n"
	<<"| | | 1+1"<<setw(37)<<setfill(' ')<<"| | |\n"
	<<"| | |"<<setw(41)<<setfill(' ')<<"| | |\n"
	<<"| | |"<<setw(41)<<setfill(' ')<<"2 | | |\n"
	<<"| | |"<<setw(41)<<setfill(' ')<<"| | |\n"
	<<"| | | 6*8"<<setw(37)<<setfill(' ')<<"| | |\n"
	<<"| | |"<<setw(41)<<setfill(' ')<<"48 | | |\n"
	<<"| | |"<<setw(41)<<setfill(' ')<<"| | |\n"
	<<"| | | _"<<setw(39)<<setfill(' ')<<"| | |\n"
	<<"| | |"<<setw(41)<<setfill(' ')<<"| | |\n"
	<<"| | |"<<setw(41)<<setfill(' ')<<"| | |\n"
	<<"| | |"<<setw(41)<<setfill(' ')<<"| | |\n"
	<<"| | |"<<setw(41)<<setfill(' ')<<"| | |\n"
	<<"| | |"<<setw(41)<<setfill(' ')<<"| | |\n"
	<<"| | |"<<setw(41)<<setfill(' ')<<"| | |\n"
	<<"| | \'"<<setw(41)<<setfill('-')<<"\' | |\n"
	<<"| |"<<setw(43)<<setfill(' ')<<"| |\n"
	<<"| \'"<<setw(43)<<setfill('-')<<"\' |\n"
	<<"|"<<setw(6)<<setfill(' ')<<"M1"<<setw(8)<<setfill(' ')<<"M2"<<setw(8)<<setfill(' ')<<"M3"<<setw(8)<<setfill(' ')<<"M4"<<setw(8)<<setfill(' ')<<"M5"<<setw(7)<<setfill(' ')<<"|\n"
	<<"|  ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(10)<<setfill('-')<<",  |\n"
	<<"|"<<setw(6)<<setfill(' ')<<"| F1"<<setw(5)<<setfill(' ')<<"| |"<<setw(34)<<setfill(' ')<<"F2 | |  F3 | |  F4 | | F5  |  |\n"
	<<"|  `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(10)<<setfill('-')<<"`  |\n"
	<<"|"<<setw(9)<<setfill('-')<<"."<<setw(8)<<setfill('_')<<""<<setw(11)<<setfill(' ')<<""<<setw(9)<<setfill('_')<<","<<setw(9)<<setfill('-')<<"|\n|"
	<<setw(18)<<setfill(' ')<<"`"<<setw(9)<<setfill('-')<<"`"<<setw(18)<<setfill(' ')<<"|\n"
	<<"|"<<setw(46)<<setfill(' ')<<"|\n|"
	<<setw(15)<<setfill(' ')<<"QUIT"<<setw(8)<<setfill(' ')<<"MODE"<<setw(23)<<setfill(' ')<<setw(12)<<setfill(' ')<<"_,-._"<<setw(11)<<setfill(' ')<<"|\n|"
	<<"  ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(6)<<setfill('-')<<","<<setw(8)<<setfill('-')<<"  /\\ \\_^_/ /\\"<<setw(8)<<setfill(' ')<<"|\n|"
	<<"  | 2nd | | EXIT| | MORE| / /"<<setw(4)<<setfill(' ')<<"|"<<setw(6)<<setfill(' ')<<"\\ \\"<<setw(7)<<setfill(' ')<<"|\n|"
	<<"  `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(7)<<setfill('-')<<"` "<<"|<|"<<setw(4)<<setfill(' ')<<"0"<<setw(6)<<setfill(' ')<<"|>|"<<setw(7)<<setfill(' ')<<"|\n|"
	<<setw(8)<<setfill(' ')<<"alpha"<<setw(9)<<setfill(' ')<<"LINK x"<<setw(6)<<setfill(' ')<<"INS"<<setw(16)<<setfill(' ')<<"\\ \\  _|_  / /"<<setw(7)<<setfill(' ')<<"|\n|"
	<<setw(3)<<setfill(' ')<<"."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(6)<<setfill('-')<<","<<setw(15)<<setfill(' ')<<"\\/ / ⍱ \\ \\/"<<setw(8)<<setfill(' ')<<"|\n|"
	<<setw(25)<<setfill(' ')<<"|ALPHA| |x-VAR| | DEL |"<<setw(10)<<setfill(' ')<<"-._,-"<<setw(11)<<setfill(' ')<<"|\n|"
	<<"  `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(6)<<setfill('-')<<"`"<<setw(21)<<setfill(' ')<<"|\n|"
	<<setw(23)<<setfill(' ')<<"SOLVER  SIMULT  POLY"<<setw(16)<<setfill(' ')<<"CATLG-VARS"<<setw(7)<<setfill(' ')<<"|\n|"
	<<"  ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(10)<<setfill('-')<<",  |\n"
	<<"|  |GRAPH| |TABLE| | PRGM| |CUSTM| |CLEAR|  |\n"
	<<"|  `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(11)<<setfill('-')<<"`  |\n|"
	<<setw(36)<<setfill(' ')<<"10x A SIN-1 B COS-1 C TAN-1 D  pi"<<setw(3)<<setfill(' ')<<"E"<<setw(6)<<setfill(' ')<<"|\n"
	<<"|  ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(10)<<setfill('-')<<",  |\n"
	<<"|  | LOG | | SIN | | COS | | TAN | |  ^  |  |\n"
	<<"|  `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(11)<<setfill('-')<<"`  |\n|"
	<<setw(28)<<setfill(' ')<<"ex  F  x-1  G  [  H  ]  I"<<setw(12)<<setfill(' ')<<"CALC J"<<setw(5)<<setfill(' ')<<"|\n"
	<<"|  ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(10)<<setfill('-')<<",  |\n"
	<<"|  | LN  | |  EE | |  (  | |  )  | |"<<setw(10)<<setfill(' ')<<"|  |\n"
	<<"|  `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(11)<<setfill('-')<<"`  |\n|"
	<<setw(40)<<setfill(' ')<<"./`  K  MATRX L VECTR  CPLX N  MATH O"<<setw(5)<<setfill(' ')<<"|\n"
	<<"|  ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(10)<<setfill('-')<<",  |\n"
	<<"|  | X2  | |  7  | |  8  | |  9  | |  x  |  |\n"
	<<"|  `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(11)<<setfill('-')<<"`  |\n|"
	<<setw(40)<<setfill(' ')<<"/_   P  CONS Q  CONV R SRRNG S LIST T"<<setw(5)<<setfill(' ')<<"|\n"
	<<"|  ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(10)<<setfill('-')<<",  |\n"
	<<"|  |  ,  | |  4  | |  5  | |  6  | |  -  |  |\n"
	<<"|  `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(10)<<setfill('-')<<"`  |\n"
	<<"|  RCL  =  BASE U  TEST V  MEM  W  STAT X"<<setw(5)<<setfill(' ')<<"|\n"
	<<"|  ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(10)<<setfill('-')<<",  |\n"
	<<"|  | STO>| |  1  | |  2  | |  3  | |  +  |  |\n"
	<<"|  `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(11)<<setfill('-')<<"`  |\n|"
	<<setw(39)<<setfill(' ')<<"OFF   CHAR Y  :   z  ANS _   ENTRY"<<setw(6)<<setfill(' ')<<"|\n"
	<<"|  ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(8)<<setfill('-')<<", ."<<setw(10)<<setfill('-')<<",  |\n"
	<<"|  | ON  | |  0  | |  .  | | (-) | |ENTER|  |\n"
	<<"|  `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(8)<<setfill('-')<<"` `"<<setw(13)<<setfill('-')<<"`  |\n|  "
	<<setw(7)<<setfill('-')<<""<<setw(38)<<setfill(' ')<<"|\n`\\"<<setw(44)<<setfill(' ')<<"/`\n"
	<<setw(6)<<setfill(' ')<<"`-._"<<setw(38)<<setfill(' ')<<".-`\n"
	<<setw(12)<<setfill(' ')<<"`--.__"<<setw(28)<<setfill(' ')<<"__.-`\n"
	<<setw(20)<<setfill(' ')<<"``----.."<<setw(17)<<setfill('_')<<",,--->▯\n";
	return 0;
	} 
